version: '3.8'

services:
  api:
    container_name: saulter_c
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_CONNECTION=postgres
      - PORT=${PORT}
      - HOST=db
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./src:/app/src
    ports:
      - 9090:9090
  db:
    container_name: saulter-db_c
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
